from core.repo_manager import clone_repo, get_python_files
from agent.analyzer import has_too_many_nested_ifs
from agent.refactor import refactor_code
from core.repo_manager import write_and_commit


REPO_URL = "https://github.com/tamatamjagadeesh/ai-refactor-test-repo.git"
LOCAL_REPO_PATH = "./target_repo"

def main():
    clone_repo(REPO_URL, LOCAL_REPO_PATH)

    py_files = get_python_files(LOCAL_REPO_PATH)

    for file in py_files:
        print("\nAnalyzing file:", file)
        with open(file, "r", encoding="utf-8") as f:
            code = f.read()

        is_bad, reason = has_too_many_nested_ifs(code)

        if is_bad:
            print("❌ BAD CODE DETECTED")
            print("Reason:", reason)

            print("\n🤖 Calling Gemini refactor...\n")
            new_code = refactor_code(code)

            if new_code:
                branch_name = "ai-refactor-nested-if"
                write_and_commit(
                    LOCAL_REPO_PATH,
                    file,
                    new_code,
                    branch_name
                )
                from core.repo_manager import push_branch
                from github_api.pr_creator import create_pull_request

                repo_name = "ai-refactor-test-repo"

                push_branch(LOCAL_REPO_PATH, branch_name)

                create_pull_request(
                    repo_name=repo_name,
                    branch_name=branch_name,
                    title="AI Refactor: simplify nested if logic",
                    body="This PR was automatically generated by an autonomous AI refactoring agent."
                )

            else:
                print("❌ Refactoring failed")
        else:
            print("✅ Code is clean")

if __name__ == "__main__":
    main()
